# Generated by Django 3.0.8 on 2020-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='guest', max_length=25),
        ),
    ]
