# Generated by Django 3.0.8 on 2020-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_auto_20200717_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default='content'),
        ),
    ]
