# Generated by Django 3.0.8 on 2020-07-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_auto_20200717_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
